publish to leaf topics only (#137)
wmo-im/wis2-topic-hierarchy pull request #146
Opened 2024-06-03 03:02 UTC by tomkralidis

Fixes #137 

I've also renamed the "Publishing guidelines" section to just "Publishing" (i.e. requirements != guidelines).

2024-06-03 07:22 UTC, amilan17 reviewed
We need to talk with TT-NWPMD first. Topics in that team were created with the knowledge that they did not have to go down to the last leaf...

2024-06-13 13:43 UTC, david-i-berry commented
@efucile is this suitable for fast track? this is the addition of new practices (SHALL) and not just code table entries. Previously used valid topics will become invalid.

2024-06-13 13:45 UTC, david-i-berry commented on standard/requirements/core/REQ_publishing.adoc
> +^|E |Topics SHALL NOT be published to intermediary levels where sublevels are defined.
Rows 8 and 9 are new standard practices / provisions that will lead to previously valid topics becoming invalid. I'm not sure this is suitable for the FT process.

2025-02-18 12:01 UTC, josusky approved these changes

2025-03-18 11:09 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +For maximum utility and efficient management of topics, it is recommended that ``data`` is published to a detailed level of the topic hierarchy. This helps avoid the "pollution" of data messages unde
```suggestion
For maximum utility and efficient management of topics, it is recommended that ``data`` are published to a detailed level of the topic hierarchy. This helps avoid the "pollution" of data messages under the primary topics.  Publishing to a detailed level is realized by selecting a "leaf" topic (i.e. a topic in which there are no additional subtopics).
```

2025-03-18 11:13 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +
Note: Each discipline has a sub-discipline topic named ``experimental`` for publication to provisional topics.

2025-03-18 11:13 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
>  Note: Each discipline has a sub-discipline topic named ``experimental`` for publication to provisional topics.
```suggestion
```

2025-03-18 11:13 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
>  Note: Each discipline has a sub-discipline topic named ``experimental`` for publication to provisional topics.
move note to after the examples

2025-03-18 11:14 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +
```suggestion

Note: Each discipline has a sub-discipline topic named experimental for publication to provisional topics.
```

2025-03-18 11:14 UTC, amilan17 requested changes
see suggestions

2025-03-18 14:25 UTC, tomkralidis commented
TT-WISMD 2025-03-18:
- TT approves to merge

2025-03-18 14:52 UTC, merged