Issue 151
wmo-im/wis2-topic-hierarchy pull request #160
Opened 2024-06-25 12:54 UTC by amilan17

#151

2024-06-28 12:25 UTC, tomkralidis commented
TT-WISMD 2024-06-28:
- TT approves

2024-07-08 11:44 UTC, josusky approved these changes

2024-07-08 11:56 UTC, tomkralidis requested changes

2024-07-08 11:56 UTC, tomkralidis commented on topic-hierarchy/earth-system-discipline/ocean/surface-based-observations/index.csv
> +sea-level, Sea level data from tide gauges and other sources,
Remove leading spaces from Description column.

2024-07-08 15:14 UTC, amilan17 commented on topic-hierarchy/earth-system-discipline/ocean/surface-based-observations/index.csv
> +sea-level, Sea level data from tide gauges and other sources,
I think I fixed the CSV

2024-07-19 11:29 UTC, tomkralidis approved these changes

2024-07-19 11:29 UTC, merged