merge country and centre-id (#58)
wmo-im/wis2-topic-hierarchy pull request #64
Opened 2023-10-23 17:12 UTC by tomkralidis

Addresses #58.  A PDF is [attached](https://github.com/wmo-im/wis2-topic-hierarchy/files/13074092/wis2-topic-hierarchy.pdf) for reviewing in context.

2023-10-30 14:46 UTC, amilan17 approved these changes
we also need to change the requirements for identifier in WCMP2

2023-10-31 14:42 UTC, amilan17 requested changes

2023-10-31 14:42 UTC, amilan17 commented on topic-hierarchy.csv
> +5,centre-id,Acronym as specified by member and endorsed by the PR of the country and WMO
needs to be renumbered: 4, centre-id to 8,earth-system-discipline-subcategory

2023-11-06 09:59 UTC, antje-s approved these changes

2023-11-12 22:31 UTC, merged