update clause 7 for editorial changes.
wmo-im/wis2-topic-hierarchy pull request #83
Opened 2024-01-12 10:54 UTC by amilan17

Also see questions or suggestions inline.

2024-01-12 10:57 UTC, amilan17 commented on standard/requirements/core/REQ_releasing.adoc
> +^|A |Updates to the discipline topics (level 8 and beyond) will go through the WMO fast-track approval procedure.footnote:[https://community.wmo.int/en/activity-areas/wis/amendment-processes-wis-manu
add a requirement: 
"Updates for major versions will go through the WMO standard approval procedure..."

2024-01-12 11:01 UTC, amilan17 commented on standard/recommendations/core/REC_publishing.adoc
> +^|A |The topic level ``experimental`` should be used as a temporary approach until a given sub-discipline topic is approved.
normalize "sub-discipline topic"?

2024-01-12 11:02 UTC, amilan17 commented on standard/requirements/core/REQ_management.adoc
> +^|B |Discipline specific levels (level 8 and beyond) shall be proposed by domain experts and user communities.
normalize "discipline specific levels (level 8 and beyond)"?

2024-01-12 11:04 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +The WTH is managed by the WMO. Updates to the WTH are made as part of two workflows: primary levels and domain specific levels.
normalize "domain specific levels"?

2024-01-12 11:04 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +2. Domain specific topic subcategory levels (level 8 and beyond): topic structures proposed by domain experts and user communities.  These levels are a hierarchical representation of the dataset and
normalize "Domain specific topic subcategory levels (level 8 and beyond)"

2024-01-12 16:05 UTC, tomkralidis reviewed
Per comments.  Great work @amilan17

2024-01-15 15:52 UTC, amilan17 reviewed
some questions to review inline

2024-01-15 15:52 UTC, amilan17 commented on standard/requirements/core/REQ_releasing.adoc
> +//re-ordered the reqs
is this order ok?

2024-01-15 15:52 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +The primary topics apply to all data and services in WIS.  They are relational, meaning that any combination of the values in each level can be used to construct a topic applicable to a notification.
```suggestion
The primary topics apply to all data, metadata, and reports in WIS. They are relational, meaning that any combination of the values in each level can be used to construct a topic applicable to a notification.
```

2024-01-15 15:52 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +//new text
new text below

2024-01-15 15:52 UTC, amilan17 commented on standard/requirements/core/REQ_versioning.adoc
> +^|H |A renaming or removal in the WMO Notification Message encoding SHALL result in a major version update.
Is this correct? This rule seems to be for WNM, NOT WTH...

2024-01-16 01:21 UTC, tomkralidis requested changes

2024-01-16 01:21 UTC, tomkralidis commented on standard/requirements/core/REQ_versioning.adoc
> +// Is req. H correct? When a WNM changes versions then the WTH shall have a major version update too?
Yes, req. H is correct/intended.

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +The WIS2 Topic Hierarchy is included in the discovery metadata record <<see section X>>, made available by WIS brokers <<see Y>>, and selected by users to subscribe and receive notifications <<see Z>
The WIS2 Topic Hierarchy is provides a mechanism for users to subscribe to and receive data or metadata notifications, and is used in discovery metadata records as well as WIS2 brokers.

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +//change .."and services" to "..and resources"?
+1 to change "and services" to "and resources", please update?

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +The representation is encoded as a simple text string of values in each topic level separated by a "/". For example, ``origin/a/wis2/data/ca-eccc/core/weather/surface-based-observations/synop`` or ``
Change "/" to ``/``

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +.WTH example table of sub-discipline topics
Suggest we introduce this table at later time, when WTH is populated further.

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +For maximum utility and efficient management of topics, it is recommended that ``data``, ``metadata``, and ``reports`` need to be published to a detailed level. This helps with avoiding "pollution" o
Remove "reports".

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +Conformance with this standard shall be checked using the tests specified the Conformance Class Abstract Test Suite (Normative). It is published at https://schemas.wmo.int/wis2/wth/ats.
https://schemas.wmo.int/wth/a/ats

2024-01-16 01:21 UTC, tomkralidis commented on standard/sections/clause_7_normative_text.adoc
> +A zip file of all the approved topics is available at https://schemas.wmo.int/wis2/wth/a/1.0/wth.zip.
https://schemas.wmo.int/wth/a/wth-a.zip

2024-01-16 09:17 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +|WIS2 notification types (``data``, ``metadata``, or ``reports`` [from monitoring activities])
Do we remove reports from here too?

2024-01-16 09:19 UTC, amilan17 commented on standard/requirements/core/REQ_versioning.adoc
> +// Is req. H correct? When a WNM changes versions then the WTH shall have a major version update too?
Ok. I don't understand what it means....

2024-01-16 09:23 UTC, amilan17 commented on standard/sections/clause_7_normative_text.adoc
> +.WTH example table of sub-discipline topics
perhaps. @wmo-im/tt-wismd -- what do you think of this table?

2024-01-16 12:02 UTC, tomkralidis approved these changes

2024-01-16 12:03 UTC, merged