Update centre-id.csv
wmo-im/wis2-topic-hierarchy pull request #87
Opened 2024-01-22 20:56 UTC by solson-nws

Updated centre-id for NWS

2024-01-22 22:52 UTC, tomkralidis requested changes

2024-01-22 22:52 UTC, tomkralidis commented on topic-hierarchy/centre-id.csv
> +us-noaa-nws,National Weather Service
@solson-nws just wondering if NOAA should be included here in the description?  And possibly expanded?  So:

"National Oceanic and Atmospheric Administration, National Weather Service"

2024-01-23 01:35 UTC, solson-nws commented on topic-hierarchy/centre-id.csv
> +us-noaa-nws,National Weather Service
Yes, that's probably a good idea

2024-01-23 01:52 UTC, tomkralidis approved these changes

2024-01-23 01:52 UTC, merged